---
- name: Set Fedora package lists
  ansible.builtin.set_fact:
    os_pkgs:
      # Utils
      - bash-completion
      - bind-utils
      - file
      - gettext
      - htop
      - jq
      - nmap
      - nodejs-npm
      - nvtop
      - openssl
      - pciutils
      - pinentry
      - pipx
      - tmux
      - usbutils

      # Blog stuff
      - lowdown
      - rclone

      - ffmpeg
      - ImageMagick
      - pngcrush
      - yt-dlp+secretstorage

      - fzf
      - fd-find
      - ripgrep

      - neovim
      - python3-neovim

      # DevOps stuff
      - ansible
      - python3-ansible-lint
      - python3-kubernetes

      - awscli

      - helm
      - kubernetes-client

      - terraform-1.10.*
      - terraform-ls

      # Programming Languages
      - cmake
      - gcc
      - ninja-build

      - golang
      - gopls

      - python3-lsp-server+all

      - ruby
      - rubygem-jekyll
      - rubygem-puppet-lint

      - rust
      - rust-analyzer
      - cargo

      - ShellCheck

    npm_pkgs:
      - "@ansible/ansible-language-server"
      - bash-language-server
      - vim-language-server
      - yaml-language-server

- name: Add RPMFusion repos
  ansible.builtin.dnf:
    state: present
    name: "https://mirrors.rpmfusion.org/{{ item }}/fedora/\
      rpmfusion-{{ item }}-release-{{ ansible_distribution_major_version }}.noarch.rpm"
    disable_gpg_check: true
  loop:
    - free
    - nonfree

- name: Add Hashicorp repo
  ansible.builtin.yum_repository:
    state: present
    name: hashicorp
    description: Hashicorp Stable - $basearch
    baseurl: https://rpm.releases.hashicorp.com/fedora/$releasever/$basearch/stable
    enabled: true
    gpgcheck: true
    gpgkey: https://rpm.releases.hashicorp.com/gpg
    owner: root
    group: root
    mode: "644"

- name: Check crypto policy
  ansible.builtin.command:
    cmd: update-crypto-policies --show
  changed_when: false
  register: result

  # Allow SSH to olllllllld distros
- name: Set crypto policy to LEGACY
  ansible.builtin.command:
    cmd: update-crypto-policies --set LEGACY
  changed_when: true
  when: "result.stdout != 'LEGACY'"
