---
- name: Set Fedora package lists
  ansible.builtin.set_fact:
    os_pkgs:
      - ansible
      - awscli
      - bash-completion
      - bind-utils
      - file
      - ffmpeg
      - fzf
      - golang
      - golang-x-tools-gopls
      - helm
      - htop
      - ImageMagick
      - jq
      - kubernetes-client
      - neovim
      - nmap
      - npm
      - openssl
      - pciutils
      - pinentry
      - python3-ansible-lint
      - python3-lsp-server+all
      - python3-neovim
      - python3-pip
      - ripgrep
      - ruby
      - rubygem-jekyll
      - rubygem-puppet-lint
      - ShellCheck
      - terraform
      - terraform-ls
      - tmux
      - usbutils
      - yt-dlp

    npm_pkgs:
      - "@ansible/ansible-language-server"
      - bash-language-server
      - vim-language-server
      - yaml-language-server

- name: Add RPMFusion repos
  ansible.builtin.dnf:
    state: present
    name: "https://mirrors.rpmfusion.org/{{ item }}/fedora/\
             rpmfusion-{{ item }}-release-{{ ansible_distribution_major_version }}.noarch.rpm"
    disable_gpg_check: true
  loop:
    - free
    - nonfree

- name: Add Hashicorp repo
  ansible.builtin.yum_repository:
    state: present
    name: hashicorp
    description: Hashicorp Stable - $basearch
    baseurl: https://rpm.releases.hashicorp.com/fedora/$releasever/$basearch/stable
    enabled: true
    gpgcheck: true
    gpgkey: https://rpm.releases.hashicorp.com/gpg
    owner: root
    group: root
    mode: "644"
