---
- name: Set openSUSE package lists
  ansible.builtin.set_fact:
    os_pkgs:
      - ansible
      - ansible-lint
      - awk
      - bind-utils
      - ffmpeg
      - fzf
      - fzf-bash-completion
      - git
      - go
      - gopls
      - helm
      - htop
      - ImageMagick
      - jq
      - kubernetes-client
      - neovim
      - nmap
      - npm
      - python3-python-lsp-black
      - python3-python-lsp-server
        # Suggested packages for python-lsp-server
        # ------------------
      - python3-autopep8
      - python3-flake8
      - python3-mccabe
      - python3-pycodestyle
      - python3-pydocstyle
      - python3-pyflakes
      - python3-pylint
      - python3-rope
      - python3-whatthepatch
      - python3-yapf
        # ------------------
      - ripgrep
      - ruby
      - ruby-devel
      - ShellCheck
      - terraform
      - terraform-ls
      - tmux
      - usbutils
      - wl-clipboard
      - yt-dlp

    npm_pkgs:
      - "@ansible/ansible-language-server"
      - bash-language-server
      - vim-language-server

    ruby_gems:
      - name: puppet-lint
        version: 2.5.2
      - jekyll

  # Using the RHEL 9 repo. They're all single Go binaries anyhow.
- name: Add Hashicorp repo
  ansible.builtin.yum_repository:
    state: present
    name: hashicorp
    description: Hashicorp Stable - $basearch
    baseurl: https://rpm.releases.hashicorp.com/RHEL/9/$basearch/stable
    enabled: true
    gpgcheck: true
    gpgkey: https://rpm.releases.hashicorp.com/gpg
    owner: root
    group: root
    mode: "644"
    reposdir: /etc/zypp/repos.d
  register: result

- name: Trust Hashicorp's GPG key
  ansible.builtin.rpm_key:
    state: present
    key: https://rpm.releases.hashicorp.com/gpg
  when: result is changed

- name: Install development tools
  community.general.zypper:
    state: present
    name: devel_C_C++
    type: pattern
