---
- name: Configure Silverblue Host
  hosts: host
  gather_facts: true
  become: true
  tasks:
    - name: Set Silverblue package lists
      ansible.builtin.set_fact:
        os_pkgs: []

        flatpaks:
          - ca.desrt.dconf-editor
          - com.bitwarden.desktop
          - com.github.IsmaelMartinez.teams_for_linux
          - com.github.tchx84.Flatseal
          - com.mattjakeman.ExtensionManager
          - com.slack.Slack
          - com.vixalien.sticky
          - de.haeckerfelix.Fragments
          - io.github.celluloid_player.Celluloid
          - org.chromium.Chromium
          - org.gimp.GIMP
          - org.gnome.Aisleriot
          - org.gnome.Boxes
          - org.gnome.Calculator
          - org.gnome.Calendar
          - org.gnome.Characters
          - org.gnome.DejaDup
          - org.gnome.FileRoller
          - org.gnome.Firmware
          - org.gnome.Logs
          - org.gnome.Loupe
          - org.gnome.Mahjongg
          - org.gnome.NautilusPreviewer
          - org.gnome.Papers
          - org.gnome.Snapshot
          - org.gnome.TextEditor
          - org.gnome.Weather
          - org.gnome.baobab
          - org.gnome.clocks
          - org.remmina.Remmina
          - org.signal.Signal

    - name: Enable openh264 for Firefox
      block:
        # No dnf, so use rpm (which makes ansible-lint yell)
        - name: Check if mozilla-openh264 exists
          ansible.builtin.command:
            cmd: rpm -qi mozilla-openh264 # noqa: command-instead-of-module
          changed_when: false
      rescue:
        # No suitable module to do compound transactions like this
        - name: Replace noopenh264 with mozilla-openh264
          ansible.builtin.command:
            cmd: rpm-ostree override remove noopenh264 --install mozilla-openh264
          changed_when: true

    - name: Remove Fedora flatpak remote
      community.general.flatpak_remote:
        state: absent
        name: fedora

    - name: Install flatpaks
      community.general.flatpak:
        state: present
        name: "{{ flatpaks }}"

    - name: Desktop tasks
      when: ansible_form_factor == 'Desktop'
      block:
        - name: Disable builtin NIC on monitor
          ansible.builtin.copy:
            src: files/host/etc/udev/rules.d/viewsonic-nic.rules
            dest: /etc/udev/rules.d/
            owner: root
            group: root
            mode: "644"
            setype: udev_rules_t
          notify: Trigger udev rules

        - name: Turn off suspend on AC power for GDM
          ansible.builtin.script: files/host/gsettings_gdm.sh
          register: result
          changed_when: result.stdout == "1"

    - name: Laptop tasks
      when: ansible_form_factor == 'Notebook'
      block:
        # GNOME does this for us now :D
        - name: Ensure old battery care udev rule is gone
          ansible.builtin.file:
            path: /etc/udev/rules.d/battery-care.rules
            state: absent
          notify: Trigger udev rules

    - name: User configuration
      become: false
      block:
        - name: Link user dotfiles
          ansible.builtin.file:
            state: link
            force: true
            src: "{{ item.root + item.path }}"
            path: "~/.{{ item.path }}"
          with_community.general.filetree: "{{ playbook_dir }}/files/dotfiles/"
          when: "'/' not in item.path" # no recursion-- top level items only

        - name: Link user config dirs
          ansible.builtin.file:
            state: link
            force: true
            src: "{{ item.root + item.path }}"
            path: "~/.config/{{ item.path }}"
          with_community.general.filetree: "{{ playbook_dir }}/files/config/"
          when: item.state == 'directory' and '/' not in item.path

        - name: Hide some system apps
          ansible.builtin.copy:
            src: files/host/hidden.desktop
            dest: ~/.local/share/applications/{{ item }}.desktop
            mode: "644"
          loop:
            - org.gnome.Tour

        - name: Enable HW acceleration in Chromium flatpak
          ansible.builtin.copy:
            src: files/host/org.chromium.Chromium.desktop
            dest: ~/.local/share/applications/
            mode: "644"

        - name: Set gsettings prefs
          ansible.builtin.script: files/host/gsettings.sh
          register: result
          changed_when: result.stdout == "1"


  handlers:
    - name: Trigger udev rules
      ansible.builtin.command:
        cmd: udevadm {{ item }}
      changed_when: true
      loop:
        - control --reload
        - trigger
