#
# ~/.bash_profile
#

# Source user bashrc
if [[ -f ~/.bashrc ]]; then
    source ~/.bashrc
fi

# History options
export HISTCONTROL='ignoreboth:erasedups'

# Editor preference list
for editor in nvim vimx vim vi nano; do
    if type $editor &>/dev/null; then
        export EDITOR="$editor"
        break
    fi
done

# Install gems to user dir by default
if type gem &>/dev/null; then
    GEM_HOME="$(ruby -e 'puts Gem.user_dir')"
    export GEM_HOME

    PATH="$(ruby -e 'puts Gem.bindir'):$PATH"
    export PATH
fi

# Rust
if type cargo &>/dev/null; then
    export PATH="${HOME}/.cargo/bin:$PATH"
fi

# Go
if type go &>/dev/null; then
    export GOPATH="${HOME}/Projects/go"
    export PATH="${HOME}/Projects/go/bin:$PATH"
fi

# Homebrew
if [[ -x /home/linuxbrew/.linuxbrew/bin/brew ]]; then
    eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"

    brew_completion_script="${HOMEBREW_PREFIX}/etc/profile.d/bash_completion.sh"
    [[ -r $brew_completion_script ]] && source "$brew_completion_script"
    unset brew_completion_script
fi

# FZF
if type fzf &>/dev/null; then
    eval "$(fzf --bash)"

    fd_opts='--strip-cwd-prefix --hidden --follow'
    fd_excludes="--exclude .local/share/containers --exclude .var/app --exclude .git --exclude .terraform --exclude .ansible"

    export FZF_DEFAULT_COMMAND="fd --type f $fd_opts $fd_excludes"
    export FZF_ALT_C_COMMAND="fd --type d $fd_opts $fd_excludes"
    export FZF_ALT_C_OPTS="--preview 'tree -C {}'"
    export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"

    unset fd_opts fd_excludes
fi

# Home bin dir
export PATH="$HOME/.local/bin:$PATH"
